### ISSUE TITLE
install.ps1运行失败

### ISSUE THREAD

**Issue by magicwang1111** [WSH032/sd-webui-fast-dataset-maker#3]
win10 cuda11.8   python3.10
Creating venv...
.\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 D:\sd-webui-fast-dataset-maker\install.ps1:23 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Activate venv failed.
Install failed.

**Comment by WSH032** [comment]
是不是之前安装的时候失败过一次？
可能没正确创建虚拟环境。
检查以下有没有这个文件夹，有的话把它删了再运行试试.

![@ (CTTGBI6X6L4B_~ZWXK3L](https://github.com/WSH032/sd-webui-fast-dataset-maker/assets/126865849/ce04b94a-f282-4a99-88c9-ca5c92d60c11)

我这边复现不了这个问题

**Comment by magicwang1111** [comment]
> 是不是之前安装的时候失败过一次？ 可能没正确创建虚拟环境。 检查以下有没有这个文件夹，有的话把它删了再运行试试.
> 
> ![@ (CTTGBI6X6L4B_~ZWXK3L](https://user-images.githubusercontent.com/126865849/250000146-ce04b94a-f282-4a99-88c9-ca5c92d60c11.png)
> 
> 我这边复现不了这个问题

venv是删除了的，sdwebui我都部署过。。所以出现这个问题有点奇怪

**Comment by magicwang1111** [comment]
解决了，通过requirements.txt部署环境

**Comment by WSH032** [comment]
嗯，如果你会用pip的话，这确实也是个解决方法。`install.py` 主要是提供给不会命令的小白使用。

同样的 `install.py` 我在其他项目也用过，都没出现这种情况。
我不是太了解 虚拟环境 的具体详细，可能是主环境的python设置问题，也有可能是 `install.py` 内激活虚拟环境的代码有问题。
如果还有类似的issue，我会调查一下。
